import Image from "next/image";

export default function Home() {
  return (
    <div className="pt-20 px-2">
      <h1 className="text-3xl font-bold">MarkTrack</h1>
      <p className="text-lg">Generated by create next app</p>
    </div>
  );
}
