version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_BACKEND_URL: "http://backend:8000"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/credentials:/app/credentials
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/marktrack-655e8-firebase-adminsdk-uev46-1af6e0dced.json
