version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://127.0.0.1:8080

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - ./backend/credentials/.env:/app/credentials/.env
      - ./backend/credentials/marktrack-655e8-firebase-adminsdk-uev46-1af6e0dced.json:/app/credentials/marktrack-655e8-firebase-adminsdk-uev46-1af6e0dced.json
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/marktrack-655e8-firebase-adminsdk-uev46-1af6e0dced.json
    env_file:
      - ./backend/credentials/.env
