version: '3.8'
services:
  frontend:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_BACKEND_URL: "http://backend:8000"

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
